apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version }}-service
spec:
  selector:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
  ports:
  - protocol: "TCP"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
  {{- if not .Values.ingress }}
  type: LoadBalancer
  {{- end}}